analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart

  errors:
    omit_local_variable_types: ignore
    prefer_single_quotes: ignore
    prefer_final_fields: ignore
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - no_logic_in_create_state
    - prefer_void_to_null
    - use_key_in_widget_constructors
    - always_put_required_named_parameters_first
    - file_names
    - leading_newlines_in_multiline_strings
    - library_prefixes
    - null_closures
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - secure_pubspec_urls
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - no_duplicate_case_values
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
